
```{r}
require(quantmod) 
require(tidyquant)
require(tidyverse)
require(dplyr)
require(lubridate)
require(tidyr)
```
```{r}
spy <- tq_get("SPY",get = "stock.prices", from = "1994-01-01", to = "2020-03-31")
head(spy)
tail(spy)
```

```{r}
stock_returns <- spy %>% tq_transmute(select=adjusted, mutate_fun = periodReturn, period="monthly",col_rename = "Ra")
stock_returns

```


```{r}
sma <- spy %>% tq_transmute(select=close, mutate_fun = SMA, period="monthly",col_rename = "sma")
head(sma)
tail(sma)
```

```{r}
s <-separate(sma,col = date,into = c("year","month","day"), sep="-")
```

```{r}
sma_final <- s %>% group_by(year,month) %>% summarise(day[1],sma[1])
```

```{r}
colnames(sma_final)[colnames(sma_final) %in% c("sma[1]","day[1]")] <- c("day","sma")
```

```{r}
sma_final$date <- paste(sma_final$year,sma_final$month,sma_final$day,sep="-")
```
```{r}
sma_final$date<- as.Date(sma_final$date)
```

```{r}
# Initializing the columns 
stock_returns$strategy1<- c(1000)
stock_returns$strategy2 <- c(1000)
```

```{r}
temp <- left_join(sma_final[,c(4,5)],spy[,c(2,3)])
```

```{r}
for(i in 2:nrow(stock_returns)){
  stock_returns$strategy1[i] = (stock_returns$strategy1[i-1]+1000) * (1.0+stock_returns$Ra[i])
  
  if(temp$open[i] >= temp$sma[i] ){
       stock_returns$strategy2[i] = (stock_returns$strategy2[i-1]+1000) * (1.0+stock_returns$Ra[i])

  }
  else{
    stock_returns$strategy2[i] = stock_returns$strategy2[i-1]+1000
  }
  
}
```

```{r}
ggplot(stock_returns,mapping = aes(x = date))+geom_line(aes(y=strategy1),color="green")+geom_line(aes(y=strategy2),color="red")
```


